config/routes.rb
Rails.application.routes.draw do
  root 'transactions#show'

	resource :transaction,       only: 	[:show]
	resource :income_statement , only: 	[:show]
	resource :balance_sheet,     only: 	[:show]

  resources :header_accounts,  except: [:new, :create, :destroy]
  resources :transfers,        only: 	[:new, :create, :edit, :update]
	resources :journal_entries,  only: 	[:new, :create, :edit, :update]
	resources :checks,				   only: 	[:new, :create, :edit, :update]
	resources :expenses, 			   only: 	[:new, :create, :edit, :update]
  resources :transactions,     only: 	[:index]
  resources :folders,      		 only: 	[:index]
  resources :reports,      		 only: 	[:index]
  resources :dynamic_menus
  resources :category_types
  resources :detail_types
  resources :accounts
	resources :customers
	resources :vendors
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  layout 'dashboard'

  def detail_type_accounts
    Account.joins(detail_type: :category_type).
        where('category_type_id = :category_type_id', category_type_id: CategoryType.find_by_name('Bank'))
  end
end

app/views/layouts/dashboard/_barchart_disclaimer.html.erb
<div class="barchart-disclaimer">
  <a href="http://www.cmegroup.com/education" target="_blank" class="logo-link">
    <%= image_tag("barchart_disclaimer/cme_logo.png") %>
  </a>

  <a href="http://www.theice.com/" target="_blank" class="logo-link">
    <%= image_tag("barchart_disclaimer/ice_logo.png") %>
  </a>

  <br>

  &copy; 2016
  <a href="http://www.barchartmarketdata.com/home.php" target="_blank">Barchart.com, Inc.</a>
  Quote data provided and hosted by Barchart
  <a href="http://www.barchartmarketdata.com/home.php" target="_blank">Market Data</a>
  Solutions.

  <br>

  Information is provided 'as-is' and solely for informational purposes, not for trading
  purposes or advice, and is delayed. To see all exchange delays and terms of use please see
  <a href="http://fulldemo.websol.barchart.com/demo/futures.php?page=agreement&a=b" target="_blank">disclaimer</a>.
</div>

app/views/layouts/dashboard/_navigation.html.erb
<div class="logo">
  <i class="icon-logo"></i>
  <span class="harvest">Accounting</span><span class="profit">App</span>
</div>

<ul class="default">
  <li class="section">
    <span class="title">Finance</span>

    <li class="fields">
      <%= link_to transaction_path do %>
          Transactions
      <% end %>
    </li>

    <li class="fields">
      <%= link_to dynamic_menus_path do %>
          Dynamic Menu
      <% end %>
    </li>

    <li class="fields">
      <%= link_to reports_path do %>
          Reports
      <% end %>
    </li>
  </li>

  <li class="section">
    <span class="title">Settings</span>

    <li class="fields">
      <%= link_to accounts_path do %>
          Chart of Accounts
      <% end %>
    </li>

    <li class="fields">
      <%= link_to vendors_path do %>
          Vendors
      <% end %>
    </li>

    <li class="fields">
      <%= link_to customers_path do %>
          Customers
      <% end %>
    </li>
  </li>
</ul>

app/views/layouts/dashboard/_vue_components.html.erb
<div id="v-page-status"></div>