config/routes.rb
Rails.application.routes.draw do
  root 'transactions#show'

	resource :transaction,       only: 	[:show]
	resource :income_statement , only: 	[:show]
	resource :balance_sheet,     only: 	[:show]

  resources :header_accounts,  except: [:new, :create, :destroy]
  resources :transfers,        only: 	[:new, :create, :edit, :update]
	resources :journal_entries,  only: 	[:new, :create, :edit, :update]
	resources :checks,				   only: 	[:new, :create, :edit, :update]
	resources :expenses, 			   only: 	[:new, :create, :edit, :update]
  resources :transactions,     only: 	[:index]
  resources :folders,      		 only: 	[:index]
  resources :reports,      		 only: 	[:index]
  resources :dynamic_menus
  resources :category_types
  resources :detail_types
  resources :accounts
	resources :customers
	resources :vendors
end

app/models/vendor.rb
class Vendor < ApplicationRecord
	validates :name, :phone_number, :email, :address, presence: true
	validates :email, uniqueness: {case_sensitive: false}, email: true

	has_many :folders
end

app/controllers/vendors_controller.rb
class VendorsController < DashboardsController
	def new
		@vendor = Vendor.new

		render :new, locals: {vendor: @vendor}
	end

	def create
		use_case = CreateVendor.call(vendor_params: vendor_params)

		if use_case.success?

			redirect_to use_case.vendor, notice: 'Vendor has successfully been saved.'
		else
			render :new, locals: {vendor: use_case.vendor}
		end
	end

	def show
		@vendor = Vendor.find(params[:id])

		render :show, locals: {vendor: @vendor}
	end

	def edit
		@vendor = Vendor.find(params[:id])

		render :edit, locals: {vendor: @vendor}
	end

	def update
		use_case = UpdateVendor.call(vendor_id: params[:id], vendor_params: vendor_params)

		if use_case.success?

			redirect_to use_case.vendor, notice: 'Vendor has successfully been updated.'
		else
			render :edit, locals: {vendor: use_case.vendor}
		end
	end

	def index
		@vendors = Vendor.all

		render :index, locals: {vendors: @vendors}
	end

	def destroy
		vendor = Vendor.find(params[:id])
		vendor.destroy

		redirect_to vendors_url, alert: 'Vendor deleted.'
	end

	private

	def vendor_params
		params.require(:vendor).permit(:name, :address, :email, :phone_number)
	end
end

app/views/vendors/_form.html.erb
<div class="content">
  <%= simple_form_for(vendor, html: { class: "field-form vertical" }) do |f| %>
      <%= f.input :name %>
      <%= f.input :email, as: :email %>
      <%= f.input :phone_number %>
      <%= f.input :address %>
      <div class="input submit">
        <%= f.button :submit, "Save", class: 'button' %>
        <%= link_to 'Cancel', vendors_path, class: 'button' %>
      </div>
  <% end %>
</div>

app/views/vendors/edit.html.erb
<div class="panel">
  <div class="content">
    <%= link_to 'All Vendors', vendors_path, class: 'button' %>
  </div>
</div>
<div class="panel">
  <div class="title">
    Edit Vendor
  </div>

  <%= render 'form', vendor: vendor %>
</div>

app/views/vendors/index.html.erb
<div class="panel">
  <div class="title">
    <%= link_to 'New Vendor', new_vendor_path, class: 'button' %>
  </div>
</div>
<div class="markets panel">
  <div class="title">
    All Vendors
  </div>

  <div class="content">
    <table>
      <thead>
      <tr>
        <th class="month">Vendor</th>
        <th class="month">Phone</th>
        <th class="month">Email</th>
        <th class="number">Actions</th>
      </tr>
      </thead>

      <tbody>
      <% vendors.each do |vendor| %>
          <tr>
            <td class="month"><%= link_to vendor.name, vendor_path(vendor) %> </td>
            <td class="month"><%= vendor.phone_number %></td>
            <td class="month"><%= vendor.email %> </td>
            <td class="number">
              <%= link_to edit_vendor_path(vendor), class: '' do %>
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              <% end %>
              <%= link_to vendor_path(vendor), method: :delete, data: {confirm: 'Are you sure?'}, class: '' do %>
                  <i class="fa fa-times" aria-hidden="true"></i>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/vendors/new.html.erb
<div class="panel">
  <div class="content">
    <%= link_to 'All Vendors', vendors_path, class: 'button' %>
  </div>
</div>
<div class="panel">
  <div class="title">
    Create Vendor
  </div>

  <%= render 'form', vendor: vendor %>
</div>

app/views/vendors/show.html.erb
<div class="panel">
  <div class="title">
    <%= vendor.name %>
  </div>

  <div class="content">
    <p><b>Name:</b>    <%= vendor.name %> </p>
    <p><b>Email:</b>   <%= vendor.email %> </p>
    <p><b>Phone:</b>   <%= vendor.phone_number %> </p>
    <p><b>Address:</b> <%= vendor.address %> </p>
  </div>
</div>
<div class="panel">
  <div class="content">
    <%= link_to 'Edit', edit_vendor_path(vendor), class: 'button' %>
    <%= link_to 'All Vendors', vendors_path, class: 'button' %>
  </div>
</div>