config/routes.rb
Rails.application.routes.draw do
  root 'transactions#show'

	resource :transaction,       only: 	[:show]
	resource :income_statement , only: 	[:show]
	resource :balance_sheet,     only: 	[:show]

  resources :header_accounts,  except: [:new, :create, :destroy]
  resources :transfers,        only: 	[:new, :create, :edit, :update]
	resources :journal_entries,  only: 	[:new, :create, :edit, :update]
	resources :checks,				   only: 	[:new, :create, :edit, :update]
	resources :expenses, 			   only: 	[:new, :create, :edit, :update]
  resources :transactions,     only: 	[:index]
  resources :folders,      		 only: 	[:index]
  resources :reports,      		 only: 	[:index]
  resources :dynamic_menus
  resources :category_types
  resources :detail_types
  resources :accounts
	resources :customers
	resources :vendors
end

app/models/dynamic_menu.rb
class DynamicMenu < ApplicationRecord
  has_many :dynamic_menus_detail_types, dependent: :destroy
  has_many :detail_types, through: :dynamic_menus_detail_types

  validates :name, :description, :from_list, :to_list, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :detail_type_ids, presence: true
end

app/controllers/dynamic_menus_controller.rb
class DynamicMenusController < DashboardsController
  def new
    @dynamic_menu = DynamicMenu.new

    render :new, locals: {
        dynamic_menu: @dynamic_menu,
        lists: DetailType.order(:name),
        from_list_ids: [],
        to_list_ids: []
    }
  end

  def create
    use_case = CreateDynamicMenu.call(dynamic_menu_params: dynamic_menu_params)
    if use_case.success?

      redirect_to use_case.dynamic_menu, notice: use_case.message
    else
      render :new, locals: {
          dynamic_menu: use_case.dynamic_menu,
          lists: DetailType.order(:name),
          from_list_ids: use_case.from_list.map(&:id),
          to_list_ids: use_case.to_list.map(&:id)
      }
    end
  end

  def show
    @dynamic_menu = DynamicMenu.find(params[:id])

    from_list = @dynamic_menu.detail_types.find(@dynamic_menu.from_list)
    to_list   = @dynamic_menu.detail_types.find(@dynamic_menu.to_list)

    render :show, locals: {
        dynamic_menu: @dynamic_menu,
        from_list: from_list.map(&:name),
        to_list: to_list.map(&:name)
    }
  end

  def edit
    @dynamic_menu = DynamicMenu.find(params[:id])
    from_list_ids = @dynamic_menu.from_list
    to_list_ids = @dynamic_menu.to_list

    render :edit, locals: {
        dynamic_menu: @dynamic_menu,
        lists: DetailType.order(:name),
        from_list_ids: from_list_ids,
        to_list_ids: to_list_ids
    }
  end

  def update
    use_case = UpdateDynamicMenu.call(dynamic_menu_id: params[:id], dynamic_menu_params: dynamic_menu_params)
    if use_case.success?

      redirect_to use_case.dynamic_menu, notice: use_case.message
    else
      render :edit, locals: {
          dynamic_menu: use_case.dynamic_menu,
          lists: DetailType.order(:name),
          from_list_ids: use_case.from_list.map(&:id),
          to_list_ids: use_case.to_list.map(&:id)
      }
    end
  end

  def index
    @dynamic_menus = DynamicMenu.includes(:detail_types).all

    render :index, locals: {dynamic_menus: @dynamic_menus}
  end

  def destroy
    dynamic_menu = DynamicMenu.find(params[:id])
    dynamic_menu.destroy

    redirect_to dynamic_menu, alert: 'You removed dynamic menu'
  end

  private

  def dynamic_menu_params
    params.require(:dynamic_menu).permit(:name, :description, from_list: [], to_list: [], category_ids: [])
  end
end

app/views/dynamic_menus/_form.html.erb
<div class="content">
  <%= simple_form_for(dynamic_menu, html: { class: "field-form vertical" }) do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :from_list, collection: lists, input_html: { multiple: true }, selected: from_list_ids %>
      <%= f.input :to_list, collection: lists, input_html: { multiple: true }, selected: to_list_ids %>
      <div class="input submit">
        <%= f.button :submit, "Save", class: 'button' %>
        <%= link_to 'Cancel', dynamic_menus_path, class: 'button' %>
      </div>
  <% end %>
</div>

app/views/dynamic_menus/edit.html.erb
<div class="panel">
  <div class="content">
    <%= link_to 'All dynamic menus', dynamic_menus_path, class: 'button' %>
  </div>
</div>
<div class="panel">
  <div class="title">
    Edit a Dynamic Menu
  </div>

  <%= render 'form', dynamic_menu: dynamic_menu,
             lists: lists,
             from_list_ids: from_list_ids,
             to_list_ids: to_list_ids %>
</div>

app/views/dynamic_menus/index.html.erb
<div class="panel">
  <div class="title">
    <%= link_to 'New Dynamic Menu', new_dynamic_menu_path, class: 'button' %>
  </div>
</div>
<div class="markets panel">
  <div class="title">
    All Dynamic Menus
  </div>

  <div class="content">
    <table>
      <thead>
      <tr>
        <th class="month">ID</th>
        <th class="month">Name</th>
        <th class="month">Description</th>
        <th class="month">From lists</th>
        <th class="month">To lists</th>
        <th class="number">Actions</th>
      </tr>
      </thead>

      <tbody>
      <% dynamic_menus.each do |dynamic_menu| %>
          <tr>
            <td class="month"><%= link_to dynamic_menu.id, dynamic_menu_path(dynamic_menu) %> </td>
            <td class="month"><%= dynamic_menu.name %> </td>
            <td class="month"><%= dynamic_menu.description %> </td>
            <td class="month">
              <% dynamic_menu.detail_types.where(id: dynamic_menu.from_list).each do |detail_type| %>
                <span><%= detail_type.name %></span>
              <% end %>
            </td>
            <td class="month">
              <% dynamic_menu.detail_types.where(id: dynamic_menu.to_list).each do |detail_type| %>
                <span><%= detail_type.name %></span>
              <% end %>
            </td>
            <td class="number">
              <%= link_to edit_dynamic_menu_path(dynamic_menu), class: '' do %>
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              <% end %>
              <%= link_to dynamic_menu_path(dynamic_menu), method: :delete, data: {confirm: 'Are you sure?'}, class: '' do %>
                  <i class="fa fa-times" aria-hidden="true"></i>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dynamic_menus/new.html.erb
<div class="panel">
  <div class="content">
    <%= link_to 'All dynamic menus', dynamic_menus_path, class: 'button' %>
  </div>
</div>
<div class="panel">
  <div class="title">
    Create a new Category
  </div>

  <%= render 'form', dynamic_menu: dynamic_menu,
             lists: lists,
             from_list_ids: from_list_ids,
             to_list_ids: to_list_ids %>
</div>

app/views/dynamic_menus/show.html.erb
<div class="panel">
  <div class="title">
    <%= dynamic_menu.name %>
  </div>

  <div class="content">
    <p><b>Name:</b> <%= dynamic_menu.name %> </p>
    <p><b>Description:</b> <%= dynamic_menu.description %> </p>
    <p><b>Account lists(For):</b>
      <% from_list.each do |list| %>
        <%= list %>
      <% end %>
    </p>
    <p><b>Account lists(To:):</b>
      <% to_list.each do |list| %>
        <%= list %>
      <% end %>
    </p>
  </div>
</div>
<div class="panel">
  <div class="content">
    <%= link_to 'Edit', edit_dynamic_menu_path(dynamic_menu), class: 'button' %>
    <%= link_to 'All Dynamic Menus', dynamic_menus_path, class: 'button' %>
  </div>
</div>