config/routes.rb
Rails.application.routes.draw do
  root 'transactions#show'

	resource :transaction,       only: 	[:show]
	resource :income_statement , only: 	[:show]
	resource :balance_sheet,     only: 	[:show]

  resources :header_accounts,  except: [:new, :create, :destroy]
  resources :transfers,        only: 	[:new, :create, :edit, :update]
	resources :journal_entries,  only: 	[:new, :create, :edit, :update]
	resources :checks,				   only: 	[:new, :create, :edit, :update]
	resources :expenses, 			   only: 	[:new, :create, :edit, :update]
  resources :transactions,     only: 	[:index]
  resources :folders,      		 only: 	[:index]
  resources :reports,      		 only: 	[:index]
  resources :dynamic_menus
  resources :category_types
  resources :detail_types
  resources :accounts
	resources :customers
	resources :vendors
end

app/controllers/transactions_controller.rb
class TransactionsController < DashboardsController
	def show
		render :show
	end

	#TODO remove this action
	def index
		@transactions = Transaction.all

		render :index, locals: {transactions: @transactions}
	end
end

app/views/transactions/index.html.erb
<div class="markets panel">
  <div class="title">
    All transactions
  </div>

  <div class="content">
    <table>
      <thead>
      <tr>
        <th class="month">Journal Entry ID</th>
        <th class="month">Amount</th>
        <th class="month">Debit Account</th>
        <th class="month">Credit Account</th>
        <!--<th class="number">Actions</th>-->
      </tr>
      </thead>

      <tbody>
      <% transactions.each do |transaction| %>
          <tr>
            <td class="month"><%= link_to transaction.id, transaction_path(transaction) %> </td>
            <td class="month"><%= transaction.amount %> </td>
            <td class="month"><%= transaction.source_account.name if transaction.source_account %> </td>
            <td class="month"><%= transaction.target_account.name if transaction.target_account %> </td>
            <td class="number">
              <%# link_to edit_transaction_path(transaction), class: '' do %>
                  <!--<i class="fa fa-pencil-square-o" aria-hidden="true"></i>-->
              <%# end %>
              <%# link_to transaction_path(transaction), method: :delete, data: {confirm: 'Are you sure?'}, class: '' do %>
                  <!--<i class="fa fa-times" aria-hidden="true"></i>-->
              <%# end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/transactions/show.html.erb
<div class="panel">
  <div class="title transactions-title">
    <div class="name">
      <span>Transactions</span>
    </div>
    <div class="transactions-buttons">
      <div class="button-wrapper">
        <%= link_to new_journal_entry_path, class: 'button' do %>
            <i class="fa fa-plus"></i>
            Journal Entry
        <% end %>
      </div>

      <div class="button-wrapper">
        <%= link_to new_transfer_path, class: 'button' do %>
            <i class="fa fa-plus"></i>
            Transfer
        <% end %>
      </div>

      <div class="button-wrapper">
        <%= link_to new_expense_path, class: 'button' do %>
            <i class="fa fa-plus"></i>
            Expense
        <% end %>
      </div>

      <div class="button-wrapper">
        <%= link_to new_check_path, class: 'button' do %>
            <i class="fa fa-plus"></i>
            Check
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="transactions">
  <div class="panel">
    <div class="title">
      See Transactions
    </div>

    <div class="content">
      <div class="link">
        <%= link_to 'Past 30 days', folders_path(filter_by: 'past_thirty_days') %>
      </div>

      <div class="link">
        <%= link_to 'Past 60 days', folders_path(filter_by: 'past_sixty_days') %>
      </div>

      <div class="link">
        <%= link_to 'Past 90 days', folders_path(filter_by: 'past_ninety_days') %>
      </div>

      <div class="link">
        <%= link_to 'All Dates', folders_path(filter_by: 'all') %>
      </div>
    </div>
  </div>

  <div class="panel">
    <div class="title">
      Transaction TO-DO's
    </div>

    <div class="content">

    </div>
  </div>
</div>